Repository Git-For-Geeks/Calculator, pull requests merged in 2022-10, with the labels that each got.

#5 fixed power of (^) button
  script/script.js
Labels: medium, git-for-geeks, hacktoberfest-accepted

#6 Fixed issue related to toggle button
  index.html
  script/script.js
Labels: easy, git-for-geeks, hacktoberfest-accepted

#9 Calculator
  index.html
  style.css
  style/style.css
Labels: easy, git-for-geeks, hacktoberfest-accepted

#11 Added sin, cos, tan and log
  index.html
  script/script.js
  style/style.css
Labels: medium, git-for-geeks, hacktoberfest-accepted

#8 Hover effect added
  index.html
  style/style.css
Labels: medium, git-for-geeks, hacktoberfest-accepted

#12 issue resolved
  index.html
Labels: easy, git-for-geeks
